enum constants {
  GET_CAROUSELS = 'GET_CAROUSELS',
  GET_GUESSES = 'GET_GUESSES',
  GET_CHANNELS = 'GET_CHANNELS',
  CHANGE_CHANNELS_LOADING = 'CHANGE_CHANNELS_LOADING',
}

export default constants;
