enum constants {
  GET_CAROUSELS = 'GET_CAROUSELS',
  GET_GUESSES = 'GET_GUESSES',
  GET_CHANNELS = 'GET_CHANNELS',
  CHANGE_CHANNELS_LOADING = 'CHANGE_CHANNELS_LOADING',
  CHANGE_ACTIVE_CAROUSEL_INDEX = 'CHANGE_ACTIVE_CAROUSEL_INDEX',
  CHANGE_LINEAR_GRADIENT_VISIBLE = 'CHANGE_LINEAR_GRADIENT_VISIBLE',
}

export default constants;
